In [1]:
import numpy as np 

In [11]:
lst = [25,41,63,89,78,58.2,85.52]
arr = np.array(lst)
arr

array([25.  , 41.  , 63.  , 89.  , 78.  , 58.2 , 85.52])

In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [7]:
arr.dtype

dtype('float64')

In [13]:
arr 

array([25.  , 41.  , 63.  , 89.  , 78.  , 58.2 , 85.52])

In [20]:
arr[::-1]

array([85.52, 58.2 , 78.  , 89.  , 63.  , 41.  , 25.  ])

In [21]:
arr 

array([25.  , 41.  , 63.  , 89.  , 78.  , 58.2 , 85.52])

In [24]:
arr[-1:-3:-1]

array([85.52, 58.2 ])

In [25]:
arr.ndim

1

In [26]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [27]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
## 1 - 10  10
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [31]:
arr2 = np.array([[52,63,52,85],
[52,63,52,85],
[52,63,52,85]])

In [32]:
arr2

array([[52, 63, 52, 85],
       [52, 63, 52, 85],
       [52, 63, 52, 85]])

In [33]:
arr2.ndim 

2

In [34]:
arr2.shape

(3, 4)

In [35]:
arr2 

array([[52, 63, 52, 85],
       [52, 63, 52, 85],
       [52, 63, 52, 85]])

In [45]:
# [row,column]  # starting_point:ending_point:step_point
arr2[-1,-1]

85

In [49]:
arr2[2][3]

85

In [51]:
arr3 = np.arange(60).reshape(12,5)
arr3 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

In [53]:
arr3.flatten()   # ravel()  #reshape

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [56]:
np.random.random((10,2))

array([[0.87972033, 0.37994306],
       [0.38684842, 0.91465695],
       [0.87503425, 0.85898824],
       [0.0851158 , 0.63169581],
       [0.24146611, 0.96578098],
       [0.75941045, 0.11046146],
       [0.31901023, 0.57329591],
       [0.44175918, 0.74720382],
       [0.91720289, 0.1567114 ],
       [0.30399908, 0.98945587]])

In [58]:
arr = np.random.randint(1,5,10)

In [61]:
arr[-1] = 100

In [63]:
arr = np.random.randint(1,200,200)
arr 

array([137, 147,  71, 199, 100,  81, 129, 108,  38,  78,  79, 150,  38,
       115,  74,  96, 197, 155,  80,  97, 108, 187, 178, 186, 183,   9,
       116, 179, 196, 136,  23,  62, 126,  43,  28, 197,  12,  18,  95,
       104,  61,   9, 125, 126, 117, 136,  83, 151,  47,  57, 189,  95,
        64,  75, 187, 161, 151, 130,  54, 117,  17, 111,  22, 182, 113,
       137,  36,  15,   8,  70, 125,  88, 157, 114,  76,  87, 145, 152,
       143, 141,  30, 174,  43,  29, 121,  76,  31, 199,  54, 128,   3,
        13,  23,  41, 160,  97, 150, 122, 108,   7,  28,  60,  80, 162,
       118,  31,   5, 102,  31, 182, 137, 159,  99, 108, 120, 190, 148,
        91, 180, 122,  66,  27,  52, 166, 120, 124,  89, 151,   5,  45,
        71,   3, 146,  59, 113,  85, 141,  37, 110, 121, 180, 159, 179,
         6, 103,  89,  45,  23, 162,  14, 171, 134,  55, 195, 142,   4,
       117,   3, 108,  62,   5,  78, 144, 197,  85, 109, 133, 176, 146,
        20, 151, 126, 114,  31, 162,  93,  42,  75,  33,   3, 15

In [67]:
arr[arr<100].shape

(98,)

In [2]:
# [[[1,2,3],
# [4,5,6]],
# [[1,2,3],
# [4,5,6]],
# [[1,2,3],
# [4,5,6]]]

arr = np.array([[[1,2,3],
[4,5,6]],
[[1,2,3],
[4,5,6]],
[[1,2,3],
[4,5,6]]])


In [3]:
arr 

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [4]:
arr.ndim

3

In [5]:
arr.shape
# (3, 2, 3) --> (table,row , column)

(3, 2, 3)

In [7]:
arr[1]  #particular table

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a = arr[1, 0 , :]

In [18]:
arr[2,1,1:]

array([5, 6])

In [21]:
arr[2][1][1:]

array([5, 6])

In [22]:
arr[:,0,:]

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [30]:
arr1 = np.random.random((3,2))
arr1 

array([[0.10595823, 0.35040692],
       [0.6329527 , 0.3118427 ],
       [0.2537702 , 0.44558886]])

In [29]:
arr2.T

array([[0.88396137, 0.11926419, 0.61223055],
       [0.5522636 , 0.14865882, 0.78710819]])

In [31]:
arr2 = np.random.random((3,2))
arr2 

array([[0.81621181, 0.75935602],
       [0.97909838, 0.7772497 ],
       [0.85900918, 0.22780098]])

In [33]:
arr2.shape 

(3, 2)

In [39]:
np.concatenate((arr1,arr2),axis=1)

array([[0.10595823, 0.35040692, 0.81621181, 0.75935602],
       [0.6329527 , 0.3118427 , 0.97909838, 0.7772497 ],
       [0.2537702 , 0.44558886, 0.85900918, 0.22780098]])

In [40]:
arr = np.arange(10)
arr 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
arr+5 

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
arr.mean() # min , max , sum

4.5

In [48]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr1 

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr =  np.array([2,4,5])
arr 

array([2, 4, 5])

In [53]:
arr1 + arr 

array([[ 3,  6,  8],
       [ 6,  9, 11]])

In [54]:
arr2 = np.array([[1,1,1],[2,2,2]])
arr2 

array([[1, 1, 1],
       [2, 2, 2]])

In [55]:
arr1 

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
arr1 + arr2

array([[2, 3, 4],
       [6, 7, 8]])

In [71]:
arr = np.array([8,1,7])
arr 

array([8, 1, 7])

In [72]:
arr.argsort()


array([1, 2, 0], dtype=int64)

In [76]:
arr 

array([8, 1, 7])

In [78]:
arr[arr.argmax()]

8

array([3, 0, 1, 2, 4], dtype=int64)

In [58]:
arr.sort()

In [59]:
arr 

array([1, 4, 6, 7, 8])

In [61]:
arr.argsort()

array([0, 1, 2, 3, 4], dtype=int64)